const base = 'https://media.immersalive.com';
// Increment this when a media file is replaced under the same filename.
const mediaRevision = '20260929-1';
const file = (folder, name) => base + '/' + folder + '/' + encodeURIComponent(name) + '?v=' + mediaRevision;
const raw = [
  ['amc','video','AMC.mp4'],
  ['ia','video','IA.mp4'],
  ['nanana','video','NANANA.mp4'],
  ['one','video','ONE.mp4'],
  ['sea-palms','video','SEA_PALMS.mp4'],
  ['evento-1','video','Evento_1.mp4'],
  ['loop-1','video','Loop1.mp4'],
  ['loop-2','video','Loop2.mp4'],
  ['mexico','video','MEXICO.mp4'],
  ['night-city-skyline','video','Night_City_Skyline.mp4'],
  ['zen','video','Zen.mp4'],

  ['bubbles','video','Bubbles.mp4'],
  ['dark-loop','video','Dark Loop.mp4'],
  ['globo','video','Globo.mp4'],
  ['humom','video','Humom.mp4'],
  ['loop-5','video','Loop 5.mp4'],
  ['loop-beam','video','Loop Beam.mp4'],
  ['loop-fire','video','Loop Fire.mp4'],
  ['loop-light','video','Loop Light.mp4'],
  ['loop-light-1','video','Loop Light1.mp4'],
  ['loop-light-2','video','Loop light2.mp4'],
  ['loop-lluvia','video','Loop lluvia.mp4'],
  ['loop-mapa','video','Loop Mapa.mp4'],
  ['loop-ojo','video','Loop Ojo.mp4'],
  ['loop-stars','video','Loop Stars.mp4'],
  ['loop-tech-4','video','Loop Tech 4.mp4'],
  ['loop-tech-1','video','Loop Tech 1.mp4'],
  ['loop-tech-3','video','Loop tech3.mp4'],
  ['loop-tech-1-alt','video','Loop tech_1.mp4'],
  ['red-color-flowers','video','Red color flowers.mp4'],
  ['tech-2','video','Tech_2.mp4'],
  ['tech-3','video','Tech_3.mp4'],
  ['tech-a','video','Tech_A.mp4'],
  ['visual','video','Visual.mp4'],
  ['wave','video','Wave.mp4'],
  ['wave-1','video','Wave1.mp4'],

  ['epic-christmas','audio','Epic Christmas.mp3'],
  ['red-carpet','audio','Red Carpet.mp3'],
  ['selfie','audio','Selfie.mp3'],
  ['champions','audio','Champions.mp3'],
  ['chillout','audio','Chillout.mp3'],
  ['bad-times','audio','Bad Times.mp3'],
  ['digidi','audio','DIGIDI.mp3'],
  ['loop-a-garnavutka','audio','Loop A GarnaVutka.mp3'],
  ['loop-c-garnavutka','audio','Loop C GarnaVutka.mp3'],
  ['now-we-are-free','audio','Now We Are Free.mp3'],
  ['piano-drone','audio','Piano Drone.mp3'],
  ['race-win','audio','Race Win.mp3'],
  ['rise-slow','audio','Rise Slow.mp3'],
  ['sweet-dreams','audio','Sweet Dreams.mp3'],
  ['techno-session','audio','Techno Session.mp3'],
  ['techno-session-2','audio','Techno Session 2.mp3'],
  ['techno-session-3','audio','Techno Session 3.mp3']
];
function listAudiovisualResources() { return raw.map(([id,type,name]) => ({ id, type, name: name.replace(/\.(mp4|mp3)$/i,''), media_url:file(type,name), thumbnail_url:type==='video'?file('thumbs',name.replace(/\.mp4$/i,'.jpg')):'', owner_type:'immersa' })); }
module.exports = { listAudiovisualResources };
